#include "test_framework.h"

int sc__total = 0;
int sc__passed = 0;
int sc__failed = 0;
jmp_buf sc__jmp;

void run_allocator_tests(void);
void run_agent_subsystems_tests(void);
void run_crypto_tests(void);
void run_json_tests(void);
void run_wasm_tests(void); /* from test_wasm.c when built */
void run_string_tests(void);
void run_slice_tests(void);
void run_memory_tests(void);
void run_tunnel_tests(void);
void run_gateway_tests(void);
void run_auth_tests(void);
void run_security_tests(void);
void run_vault_tests(void);
void run_provider_tests(void);
void run_channel_tests(void);
void run_tool_tests(void);
void test_vtables_run(void);
void run_peripheral_tests(void);
void run_e2e_tests(void);
void run_subsystems_tests(void);
void run_config_parse_tests(void);
void run_config_migrate_tests(void);
void run_adversarial_tests(void);
void run_gateway_http_tests(void);
void run_memory_full_tests(void);
void run_tools_all_tests(void);
void run_rag_tests(void);
void run_multimodal_tests(void);
void run_retrieval_tests(void);
void run_vector_tests(void);
void run_vector_full_tests(void);
void run_infrastructure_tests(void);
void run_memory_subsystems_tests(void);
void run_http_tests(void);
void run_sse_tests(void);
void run_streaming_tests(void);
void run_websocket_tests(void);
void run_net_security_tests(void);
void run_path_security_tests(void);
void run_process_util_tests(void);
void run_prompt_tests(void);
void run_lifecycle_tests(void);
void run_observer_tests(void);
void run_session_tests(void);
void run_bus_tests(void);
void run_identity_tests(void);
void run_channel_manager_tests(void);
void run_new_modules_tests(void);
void run_provider_all_tests(void);
void run_channel_all_tests(void);
void run_meta_common_tests(void);
void run_channel_integration_tests(void);
void run_config_extended_tests(void);
void run_config_validation_tests(void);
void run_json_extended_tests(void);
void run_security_extended_tests(void);
void run_security_pipeline_tests(void);
void run_core_extended_tests(void);
void run_gateway_extended_tests(void);
void run_gateway_auth_tests(void);
void run_agent_extended_tests(void);
void run_agent_security_tests(void);
void run_agent_teams_tests(void);
void run_skills_tests(void);
void run_memory_new_tests(void);
void run_ported_modules_tests(void);
void run_cron_tests(void);
void run_subagent_tests(void);
void run_mcp_tests(void);
void run_voice_tests(void);
void run_cli_tests(void);
void run_vector_stores_tests(void);
void run_memory_engines_ext_tests(void);
void run_runtime_tests(void);
void run_channel_loop_tests(void);
void run_util_modules_tests(void);
void run_roadmap_tests(void);
void run_new_features_tests(void);
void run_oauth_tests(void);
void run_ollama_integration_tests(void);
void run_plugin_tests(void);
void run_tenant_tests(void);
void run_gmail_tests(void);
void run_imessage_extended_tests(void);
void run_intelligence_tests(void);
void run_untested_modules_tests(void);
void run_modules_coverage_tests(void);

int main(void) {
    printf("SeaClaw Test Suite\n");
    fflush(stdout);
    printf("==================\n");

    run_allocator_tests();
    run_agent_subsystems_tests();
    run_crypto_tests();
    run_wasm_tests();
    run_json_tests();
    run_string_tests();
    run_slice_tests();
    run_memory_tests();
    run_tunnel_tests();
    run_gateway_tests();
    run_auth_tests();
    run_security_tests();
    run_vault_tests();
    run_provider_tests();
    run_channel_tests();
    run_tool_tests();
    test_vtables_run();
    run_peripheral_tests();
    run_e2e_tests();
    run_subsystems_tests();
    run_config_parse_tests();
    run_config_migrate_tests();
    run_adversarial_tests();
    run_gateway_http_tests();
    run_memory_full_tests();
    run_tools_all_tests();
    run_rag_tests();
    run_multimodal_tests();
    run_retrieval_tests();
    run_vector_tests();
    run_vector_full_tests();
    run_infrastructure_tests();
    run_memory_subsystems_tests();
    run_http_tests();
    run_sse_tests();
    run_streaming_tests();
    run_websocket_tests();
    run_net_security_tests();
    run_path_security_tests();
    run_process_util_tests();
    run_prompt_tests();
    run_lifecycle_tests();
    run_observer_tests();
    run_session_tests();
    run_bus_tests();
    run_identity_tests();
    run_channel_manager_tests();
    run_new_modules_tests();
    run_provider_all_tests();
    run_channel_all_tests();
    run_meta_common_tests();
    run_channel_integration_tests();
    run_config_extended_tests();
    run_config_validation_tests();
    run_json_extended_tests();
    run_security_extended_tests();
    run_security_pipeline_tests();
    run_core_extended_tests();
    run_gateway_extended_tests();
    run_gateway_auth_tests();
    run_agent_extended_tests();
    run_agent_security_tests();
    run_agent_teams_tests();
    run_skills_tests();
    run_memory_new_tests();
    run_ported_modules_tests();
    run_cron_tests();
    run_subagent_tests();
    run_mcp_tests();
    run_voice_tests();
    run_vector_stores_tests();
    run_cli_tests();
    run_memory_engines_ext_tests();
    run_runtime_tests();
    run_channel_loop_tests();
    run_util_modules_tests();
    run_roadmap_tests();
    run_new_features_tests();
    run_oauth_tests();
    run_ollama_integration_tests();
    run_plugin_tests();
    run_tenant_tests();
    run_gmail_tests();
    run_imessage_extended_tests();
    run_intelligence_tests();
    run_untested_modules_tests();
    run_modules_coverage_tests();

    SC_TEST_REPORT();
    SC_TEST_EXIT();
}
