#include "test_framework.h"

int hu__total = 0;
int hu__passed = 0;
int hu__failed = 0;
int hu__skipped = 0;
int hu__suite_active = 1;
const char *hu__suite_filter = NULL;
const char *hu__test_filter = NULL;
jmp_buf hu__jmp;

void run_allocator_tests(void);
void run_data_loader_tests(void);
void run_agent_modules_tests(void);
void run_tot_recursive_tests(void);
void run_agent_subsystems_tests(void);
void run_crypto_tests(void);
void run_json_tests(void);
void run_wasm_tests(void); /* from test_wasm.c when built */
void run_string_tests(void);
void run_slice_tests(void);
void run_memory_tests(void);
void run_memory_util_tests(void);
void run_tunnel_tests(void);
void run_gateway_tests(void);
void run_auth_tests(void);
void run_security_tests(void);
void run_vault_tests(void);
void run_provider_tests(void);
void run_provider_http_tests(void);
void run_api_key_tests(void);
void run_channel_tests(void);
void run_tool_tests(void);
void test_vtables_run(void);
void run_peripheral_tests(void);
void run_e2e_tests(void);
void run_e2e_conversation_tests(void);
void run_e2e_agent_loop_tests(void);
void run_subsystems_tests(void);
void run_config_parse_tests(void);
void run_config_migrate_tests(void);
void run_adversarial_tests(void);
void run_adversarial_detect_tests(void);
void run_gateway_http_tests(void);
void run_memory_full_tests(void);
void run_tools_all_tests(void);
void run_rag_tests(void);
void run_multimodal_tests(void);
void run_multimodal_pipeline_tests(void);
void run_multimodal_memory_tests(void);
void run_voice_duplex_tests(void);
void run_voice_realtime_tests(void);
void run_autonomy_tests(void);
void run_retrieval_tests(void);
void run_vector_tests(void);
void run_vector_full_tests(void);
void run_infrastructure_tests(void);
void run_memory_subsystems_tests(void);
void run_http_tests(void);
void run_sse_tests(void);
void run_streaming_tests(void);
void run_websocket_tests(void);
void run_net_security_tests(void);
void run_path_security_tests(void);
void run_process_util_tests(void);
void run_prompt_tests(void);
#ifdef HU_ENABLE_PERSONA
void run_persona_tests(void);
void run_circadian_tests(void);
void run_relationship_tests(void);
void run_replay_tests(void);
void run_style_clone_tests(void);
void run_life_sim_tests(void);
void run_persona_mood_tests(void);
void run_persona_feedback_tests(void);
void run_persona_cli_tests(void);
void run_voice_maturity_tests(void);
void run_style_learner_tests(void);
#endif
void run_lifecycle_tests(void);
void run_observer_tests(void);
void run_session_tests(void);
void run_bus_tests(void);
void run_identity_tests(void);
void run_channel_manager_tests(void);
void run_new_modules_tests(void);
void run_provider_all_tests(void);
void run_channel_all_tests(void);
void run_meta_common_tests(void);
void run_channel_integration_tests(void);
void run_config_extended_tests(void);
void run_config_getters_tests(void);
void run_config_validation_tests(void);
void run_json_extended_tests(void);
void run_security_extended_tests(void);
void run_security_pipeline_tests(void);
void run_core_extended_tests(void);
void run_gateway_extended_tests(void);
void run_gateway_auth_tests(void);
void run_pairing_tests(void);
void run_agent_extended_tests(void);
void run_agent_security_tests(void);
void run_agent_teams_tests(void);
void run_skills_tests(void);
void run_memory_new_tests(void);
void run_ported_modules_tests(void);
void run_cron_tests(void);
void run_subagent_tests(void);
void run_mcp_tests(void);
void run_mcp_transport_tests(void);
void run_mcp_transport_sse_tests(void);
void run_otel_trace_tests(void);
void run_mcp_audit_tests(void);
void run_voice_tests(void);
void run_cli_tests(void);
void run_vector_stores_tests(void);
void run_memory_engines_ext_tests(void);
void run_runtime_tests(void);
void run_runtime_bundle_tests(void);
void run_channel_loop_tests(void);
void run_util_modules_tests(void);
void run_roadmap_tests(void);
void run_new_features_tests(void);
void run_oauth_tests(void);
void run_ollama_integration_tests(void);
void run_plugin_tests(void);
void run_tenant_tests(void);
void run_gmail_tests(void);
void run_imessage_extended_tests(void);
void run_intelligence_tests(void);
void run_protective_tests(void);
void run_humor_tests(void);
void run_authentic_tests(void);
void run_rag_pipeline_tests(void);
void run_persona_training_tests(void);
void run_voice_integration_tests(void);
void run_behavioral_tests(void);
void run_context_ext_tests(void);
void run_untested_modules_tests(void);
void run_modules_coverage_tests(void);
void run_coverage_new_tests(void);
void run_context_tests(void);
void run_qmd_tests(void);
void run_terminal_tests(void);
void run_tavily_tests(void);
void run_awareness_tests(void);
void run_entropy_gate_tests(void);
void run_episodic_tests(void);
void run_reflection_tests(void);
void run_input_guard_tests(void);
void run_conversation_tests(void);
void run_vision_tests(void);
void run_ab_response_tests(void);
void run_event_extract_tests(void);
void run_stm_tests(void);
void run_emotional_graph_tests(void);
void run_comfort_patterns_tests(void);
void run_emotional_moments_tests(void);
void run_graph_tests(void);
void run_fast_capture_tests(void);
void run_promotion_tests(void);
void run_consolidation_tests(void);
void run_deep_extract_tests(void);
void run_commitment_tests(void);
void run_pattern_radar_tests(void);
void run_proactive_tests(void);
void run_weather_awareness_tests(void);
void run_timing_tests(void);
void run_governor_tests(void);
void run_relationship_dynamics_tests(void);
void run_model_router_tests(void);
void run_arbitrator_tests(void);
void run_planning_tests(void);
void run_rel_dynamics_tests(void);
void run_prospective_tests(void);
void run_prospective_memory_tests(void);
void run_emotional_residue_tests(void);
void run_consolidation_engine_tests(void);
void run_conv_goals_tests(void);
void run_knowledge_tests(void);
void run_cognitive_tests(void);
#ifdef HU_ENABLE_AUTHENTIC
void run_cognitive_load_tests(void);
void run_phase9_integration_tests(void);
#endif
void run_deep_memory_tests(void);
void run_compression_tests(void);
void run_proactive_ext_tests(void);
void run_degradation_tests(void);
void run_memory_degradation_tests(void);
void run_self_awareness_tests(void);
void run_superhuman_tests(void);
void run_tool_call_parser_tests(void);
void run_tool_router_tests(void);
void run_dag_tests(void);
void run_mood_tests(void);
void run_style_tracker_tests(void);
void run_theory_of_mind_tests(void);
void run_anticipatory_tests(void);
void run_visual_content_tests(void);
void run_opinions_tests(void);
void run_life_chapters_tests(void);
void run_social_graph_tests(void);
void run_skill_system_tests(void);
void run_feeds_tests(void);
#ifdef HU_ENABLE_FEEDS
void run_apple_feeds_tests(void);
void run_news_health_email_tests(void);
#endif
#ifdef HU_ENABLE_SOCIAL
void run_social_feeds_tests(void);
#endif
#ifdef HU_ENABLE_FEEDS
void run_google_feeds_tests(void);
void run_music_feeds_tests(void);
void run_research_feeds_tests(void);
void run_research_executor_tests(void);
#endif
void run_feed_processor_tests(void);
void run_forgetting_curve_tests(void);
int run_weather_fetch_tests(void);
int run_save_for_later_tests(void);
void run_intelligence_reflection_tests(void);
void run_intelligence_skills_tests(void);
void run_skill_unified_tests(void);
void run_intelligence_cycle_tests(void);
void run_reflection_advanced_tests(void);
#ifdef HU_ENABLE_SQLITE
void run_feedback_tests(void);
#endif
void run_privacy_audit_tests(void);
void run_collab_planning_tests(void);
void run_bth_e2e_tests(void);
void run_bth_metrics_tests(void);
void run_memory_features_tests(void);
void run_agi_frontiers_tests(void);
void run_swarm_execution_tests(void);
void run_dynamic_decomposition_tests(void);
void run_agent_matching_tests(void);
void run_agent_communication_tests(void);
void run_mcts_planner_tests(void);
void run_world_model_graph_tests(void);
void run_world_simulation_tests(void);
void run_world_context_tests(void);
void run_peripheral_ctrl_tests(void);
void run_value_learning_tests(void);
void run_goal_engine_tests(void);
void run_dispatch_tests(void);
void run_policy_engine_tests(void);
void run_integration_tests(void);
void run_agent_registry_tests(void);
void run_pwa_tests(void);
#ifdef HU_ENABLE_CURL
void run_paperclip_tests(void);
#endif
#ifdef HU_ENABLE_CARTESIA
void run_cartesia_tests(void);
void run_audio_pipeline_tests(void);
void run_voice_decision_tests(void);
void run_emotion_map_tests(void);
#endif
#ifdef HU_ENABLE_ML
void run_ml_tests(void);
void run_lora_tests(void);
void run_agent_trainer_tests(void);
void run_training_data_tests(void);
#endif
void run_multigraph_tests(void);
void run_memory_graph_tests(void);
void run_experience_tests(void);
void run_experience_engine_tests(void);
void run_self_improve_loop_tests(void);
void run_a2a_tests(void);
void run_eval_tests(void);
void run_eval_judge_tests(void);
void run_eval_benchmarks_tests(void);
void run_eval_runner_tests(void);
void run_eval_history_tests(void);
void run_corrective_rag_tests(void);
void run_adaptive_rag_tests(void);
void run_self_rag_tests(void);
void run_memory_tiers_tests(void);
void run_process_reward_tests(void);
void run_dpo_tests(void);
void run_sota_e2e_tests(void);
void run_otel_tests(void);
void run_cot_audit_tests(void);
void run_moderation_tests(void);
void run_code_sandbox_tests(void);
void run_computer_use_tests(void);
void run_gui_agent_tests(void);
void run_lsp_tests(void);
void run_webrtc_tests(void);
void run_embedded_provider_tests(void);
void run_forgetting_tests(void);
void run_bootstrap_tests(void);
void run_thread_pool_tests(void);
void run_weakness_tests(void);
void run_distiller_tests(void);
void run_plan_executor_tests(void);
void run_cdp_tests(void);

static void print_usage(const char *prog) {
    printf("Usage: %s [OPTIONS]\n", prog);
    printf("  --suite=<name>   Run only suites whose name contains <name>\n");
    printf("  --filter=<name>  Run only tests whose function name contains <name>\n");
    printf("  --help           Show this help message\n");
    printf("\nExamples:\n");
    printf("  %s --suite=config          # run config-related suites\n", prog);
    printf("  %s --filter=json_parse     # run tests matching 'json_parse'\n", prog);
    printf("  %s --suite=security --filter=vault  # combine both\n", prog);
}

int main(int argc, char **argv) {
    for (int i = 1; i < argc; i++) {
        if (strncmp(argv[i], "--suite=", 8) == 0) {
            hu__suite_filter = argv[i] + 8;
        } else if (strncmp(argv[i], "--filter=", 9) == 0) {
            hu__test_filter = argv[i] + 9;
        } else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 0;
        }
    }

    printf("Human Test Suite\n");
    fflush(stdout);
    printf("==================\n");
    if (hu__suite_filter)
        printf("Suite filter: %s\n", hu__suite_filter);
    if (hu__test_filter)
        printf("Test filter:  %s\n", hu__test_filter);

    run_allocator_tests();
    run_data_loader_tests();
    run_agent_modules_tests();
    run_tot_recursive_tests();
    run_agent_subsystems_tests();
    run_crypto_tests();
    run_wasm_tests();
    run_json_tests();
    run_string_tests();
    run_slice_tests();
    run_memory_tests();
    run_memory_util_tests();
    run_tunnel_tests();
    run_gateway_tests();
    run_auth_tests();
    run_security_tests();
    run_vault_tests();
    run_provider_tests();
    run_api_key_tests();
    run_channel_tests();
    run_tool_tests();
    test_vtables_run();
    run_peripheral_tests();
    run_peripheral_ctrl_tests();
    run_value_learning_tests();
    run_goal_engine_tests();
    run_dispatch_tests();
    run_policy_engine_tests();
    run_e2e_tests();
    run_integration_tests();
    run_e2e_conversation_tests();
    run_e2e_agent_loop_tests();
    run_subsystems_tests();
    run_config_parse_tests();
    run_config_migrate_tests();
    run_adversarial_tests();
    run_adversarial_detect_tests();
    run_gateway_http_tests();
    run_memory_full_tests();
    run_tools_all_tests();
    run_rag_tests();
    run_multimodal_tests();
    run_multimodal_pipeline_tests();
    run_multimodal_memory_tests();
    run_voice_duplex_tests();
    run_voice_realtime_tests();
    run_autonomy_tests();
    run_retrieval_tests();
    run_multigraph_tests();
    run_memory_graph_tests();
    run_vector_tests();
    run_vector_full_tests();
    run_infrastructure_tests();
    run_memory_subsystems_tests();
    run_http_tests();
    run_sse_tests();
    run_streaming_tests();
    run_websocket_tests();
    run_net_security_tests();
    run_path_security_tests();
    run_process_util_tests();
    run_prompt_tests();
#ifdef HU_ENABLE_PERSONA
    run_persona_tests();
    run_circadian_tests();
    run_relationship_tests();
    run_replay_tests();
    run_style_clone_tests();
    run_life_sim_tests();
    run_persona_mood_tests();
    run_persona_feedback_tests();
    run_persona_cli_tests();
    run_voice_maturity_tests();
    run_style_learner_tests();
#endif
    run_lifecycle_tests();
    run_observer_tests();
    run_session_tests();
    run_bus_tests();
    run_identity_tests();
    run_channel_manager_tests();
    run_new_modules_tests();
    run_provider_all_tests();
    run_channel_all_tests();
    run_meta_common_tests();
    run_channel_integration_tests();
    run_config_extended_tests();
    run_config_getters_tests();
    run_config_validation_tests();
    run_json_extended_tests();
    run_security_extended_tests();
    run_security_pipeline_tests();
    run_core_extended_tests();
    run_gateway_extended_tests();
    run_gateway_auth_tests();
    run_pairing_tests();
    run_agent_extended_tests();
    run_agent_security_tests();
    run_agent_teams_tests();
    run_skills_tests();
    run_memory_new_tests();
    run_ported_modules_tests();
    run_cron_tests();
    run_subagent_tests();
    run_mcp_tests();
    run_mcp_transport_tests();
    run_mcp_transport_sse_tests();
    run_otel_trace_tests();
    run_mcp_audit_tests();
    run_voice_tests();
    run_vector_stores_tests();
    run_cli_tests();
    run_memory_engines_ext_tests();
    run_runtime_tests();
    run_runtime_bundle_tests();
    run_channel_loop_tests();
    run_util_modules_tests();
    run_roadmap_tests();
    run_new_features_tests();
    run_oauth_tests();
    run_ollama_integration_tests();
    run_plugin_tests();
    run_tenant_tests();
    run_gmail_tests();
    run_imessage_extended_tests();
    run_intelligence_tests();
    run_protective_tests();
    run_humor_tests();
    run_authentic_tests();
    run_rag_pipeline_tests();
    run_persona_training_tests();
    run_voice_integration_tests();
    run_behavioral_tests();
    run_context_ext_tests();
    run_untested_modules_tests();
    run_modules_coverage_tests();
    run_coverage_new_tests();
    run_context_tests();
    run_qmd_tests();
    run_terminal_tests();
    run_tavily_tests();
    run_awareness_tests();
    run_entropy_gate_tests();
    run_episodic_tests();
    run_reflection_tests();
    run_input_guard_tests();
    run_conversation_tests();
    run_vision_tests();
    run_ab_response_tests();
    run_event_extract_tests();
    run_stm_tests();
    run_emotional_graph_tests();
    run_comfort_patterns_tests();
    run_emotional_moments_tests();
    run_graph_tests();
    run_fast_capture_tests();
    run_promotion_tests();
    run_consolidation_tests();
    run_deep_extract_tests();
    run_commitment_tests();
    run_pattern_radar_tests();
    run_proactive_tests();
    run_weather_awareness_tests();
    run_timing_tests();
    run_governor_tests();
    run_relationship_dynamics_tests();
    run_model_router_tests();
    run_arbitrator_tests();
    run_planning_tests();
    run_rel_dynamics_tests();
#ifdef HU_ENABLE_SQLITE
    run_prospective_tests();
    run_prospective_memory_tests();
    run_emotional_residue_tests();
    run_consolidation_engine_tests();
#endif
    run_conv_goals_tests();
    run_knowledge_tests();
    run_cognitive_tests();
#ifdef HU_ENABLE_AUTHENTIC
    run_cognitive_load_tests();
    run_phase9_integration_tests();
#endif
    run_deep_memory_tests();
    run_compression_tests();
    run_proactive_ext_tests();
    run_degradation_tests();
    run_memory_degradation_tests();
    run_self_awareness_tests();
    run_superhuman_tests();
    run_tool_call_parser_tests();
    run_tool_router_tests();
    run_dag_tests();
    run_mood_tests();
    run_style_tracker_tests();
    run_theory_of_mind_tests();
    run_anticipatory_tests();
    run_visual_content_tests();
    run_opinions_tests();
    run_life_chapters_tests();
    run_social_graph_tests();
    run_skill_system_tests();
    run_feeds_tests();
#ifdef HU_ENABLE_FEEDS
    run_apple_feeds_tests();
    run_news_health_email_tests();
    run_google_feeds_tests();
    run_music_feeds_tests();
    run_research_feeds_tests();
    run_research_executor_tests();
#endif
#ifdef HU_ENABLE_SOCIAL
    run_social_feeds_tests();
#endif
    run_feed_processor_tests();
    run_forgetting_curve_tests();
    run_weather_fetch_tests();
    run_save_for_later_tests();
    run_intelligence_reflection_tests();
    run_intelligence_skills_tests();
    run_skill_unified_tests();
    run_intelligence_cycle_tests();
    run_reflection_advanced_tests();
#ifdef HU_ENABLE_SQLITE
    run_feedback_tests();
#endif
    run_privacy_audit_tests();
    run_collab_planning_tests();
    run_bth_e2e_tests();
    run_e2e_conversation_tests();
    run_bth_metrics_tests();
    run_memory_features_tests();
    run_agi_frontiers_tests();
    run_swarm_execution_tests();
    run_dynamic_decomposition_tests();
    run_agent_matching_tests();
    run_agent_communication_tests();
    run_mcts_planner_tests();
    run_world_model_graph_tests();
    run_world_simulation_tests();
    run_world_context_tests();
    run_agent_registry_tests();
    run_pwa_tests();
#ifdef HU_ENABLE_CURL
    run_paperclip_tests();
#endif
#ifdef HU_ENABLE_CARTESIA
    run_cartesia_tests();
    run_audio_pipeline_tests();
    run_voice_decision_tests();
    run_emotion_map_tests();
#endif
#ifdef HU_ENABLE_ML
    run_ml_tests();
    run_lora_tests();
    run_agent_trainer_tests();
    run_training_data_tests();
#endif

    run_experience_tests();
    run_experience_engine_tests();
    run_self_improve_loop_tests();
    run_a2a_tests();
    run_eval_tests();
    run_eval_judge_tests();
    run_eval_benchmarks_tests();
    run_eval_runner_tests();
    run_eval_history_tests();
    run_corrective_rag_tests();
    run_adaptive_rag_tests();
    run_self_rag_tests();
    run_memory_tiers_tests();
    run_process_reward_tests();
    run_dpo_tests();
    run_sota_e2e_tests();
    run_otel_tests();
    run_cot_audit_tests();
    run_moderation_tests();
    run_code_sandbox_tests();
    run_computer_use_tests();
    run_gui_agent_tests();
    run_lsp_tests();
    run_webrtc_tests();
    run_embedded_provider_tests();
    run_forgetting_tests();
    run_bootstrap_tests();
    run_thread_pool_tests();
    run_weakness_tests();
    run_distiller_tests();
    run_plan_executor_tests();
    run_cdp_tests();

    HU_TEST_REPORT();
    HU_TEST_EXIT();
}
