#include "human/core/error.h"

static const char *error_strings[] = {
    [HU_OK] = "ok",
    [HU_ERR_OUT_OF_MEMORY] = "out of memory",
    [HU_ERR_INVALID_ARGUMENT] = "invalid argument",
    [HU_ERR_NOT_FOUND] = "not found",
    [HU_ERR_ALREADY_EXISTS] = "already exists",
    [HU_ERR_NOT_SUPPORTED] = "not supported",
    [HU_ERR_PERMISSION_DENIED] = "permission denied",
    [HU_ERR_TIMEOUT] = "timeout",
    [HU_ERR_IO] = "I/O error",
    [HU_ERR_PARSE] = "parse error",
    [HU_ERR_CONFIG_INVALID] = "invalid configuration",
    [HU_ERR_CONFIG_NOT_FOUND] = "configuration not found",
    [HU_ERR_PROVIDER_UNAVAILABLE] = "provider unavailable",
    [HU_ERR_PROVIDER_AUTH] = "provider authentication failed",
    [HU_ERR_PROVIDER_RATE_LIMITED] = "provider rate limited",
    [HU_ERR_PROVIDER_RESPONSE] = "provider response error",
    [HU_ERR_CHANNEL_SEND] = "channel send failed",
    [HU_ERR_CHANNEL_START] = "channel start failed",
    [HU_ERR_CHANNEL_NOT_CONFIGURED] = "channel not configured",
    [HU_ERR_TOOL_EXECUTION] = "tool execution failed",
    [HU_ERR_TOOL_VALIDATION] = "tool input validation failed",
    [HU_ERR_TOOL_NOT_FOUND] = "tool not found",
    [HU_ERR_MEMORY_STORE] = "memory store error",
    [HU_ERR_MEMORY_RECALL] = "memory recall error",
    [HU_ERR_MEMORY_BACKEND] = "memory backend error",
    [HU_ERR_SECURITY_COMMAND_NOT_ALLOWED] = "command not allowed",
    [HU_ERR_SECURITY_HIGH_RISK_BLOCKED] = "high risk command blocked",
    [HU_ERR_SECURITY_APPROVAL_REQUIRED] = "approval required",
    [HU_ERR_SECURITY_RATE_LIMITED] = "security rate limited",
    [HU_ERR_SECURITY_LOCKOUT] = "security lockout",
    [HU_ERR_PERIPHERAL_NOT_CONNECTED] = "peripheral not connected",
    [HU_ERR_PERIPHERAL_IO] = "peripheral I/O error",
    [HU_ERR_PERIPHERAL_FLASH_FAILED] = "peripheral flash failed",
    [HU_ERR_PERIPHERAL_DEVICE_NOT_FOUND] = "peripheral device not found",
    [HU_ERR_TUNNEL_START_FAILED] = "tunnel start failed",
    [HU_ERR_TUNNEL_URL_NOT_FOUND] = "tunnel URL not found",
    [HU_ERR_GATEWAY_RATE_LIMITED] = "gateway rate limited",
    [HU_ERR_GATEWAY_BODY_TOO_LARGE] = "gateway body too large",
    [HU_ERR_GATEWAY_AUTH] = "gateway authentication failed",
    [HU_ERR_CRYPTO_ENCRYPT] = "encryption failed",
    [HU_ERR_CRYPTO_DECRYPT] = "decryption failed",
    [HU_ERR_CRYPTO_HMAC] = "HMAC failed",
    [HU_ERR_JSON_PARSE] = "JSON parse error",
    [HU_ERR_JSON_TYPE] = "JSON type mismatch",
    [HU_ERR_JSON_DEPTH] = "JSON max depth exceeded",
    [HU_ERR_INTERNAL] = "internal error",
    [HU_ERR_SUBAGENT_TOO_MANY] = "too many concurrent subagents",
    [HU_ERR_CANCELLED] = "cancelled",
    [HU_ERR_LIMIT_REACHED] = "limit reached",
    [HU_ERR_FLEET_DEPTH_EXCEEDED] = "fleet spawn depth limit exceeded",
    [HU_ERR_FLEET_SPAWN_CAP] = "fleet total spawn limit exceeded",
    [HU_ERR_FLEET_BUDGET_EXCEEDED] = "fleet budget exceeded",
};

const char *hu_error_string(hu_error_t err) {
    if (err >= 0 && err < HU_ERR_COUNT)
        return error_strings[err];
    return "unknown error";
}
