#ifndef HU_ERROR_H
#define HU_ERROR_H

typedef enum hu_error {
    HU_OK = 0,

    HU_ERR_OUT_OF_MEMORY,
    HU_ERR_INVALID_ARGUMENT,
    HU_ERR_NOT_FOUND,
    HU_ERR_ALREADY_EXISTS,
    HU_ERR_NOT_SUPPORTED,
    HU_ERR_PERMISSION_DENIED,
    HU_ERR_TIMEOUT,
    HU_ERR_IO,
    HU_ERR_PARSE,

    HU_ERR_CONFIG_INVALID,
    HU_ERR_CONFIG_NOT_FOUND,

    HU_ERR_PROVIDER_UNAVAILABLE,
    HU_ERR_PROVIDER_AUTH,
    HU_ERR_PROVIDER_RATE_LIMITED,
    HU_ERR_PROVIDER_RESPONSE,

    HU_ERR_CHANNEL_SEND,
    HU_ERR_CHANNEL_START,
    HU_ERR_CHANNEL_NOT_CONFIGURED,

    HU_ERR_TOOL_EXECUTION,
    HU_ERR_TOOL_VALIDATION,
    HU_ERR_TOOL_NOT_FOUND,

    HU_ERR_MEMORY_STORE,
    HU_ERR_MEMORY_RECALL,
    HU_ERR_MEMORY_BACKEND,

    HU_ERR_SECURITY_COMMAND_NOT_ALLOWED,
    HU_ERR_SECURITY_HIGH_RISK_BLOCKED,
    HU_ERR_SECURITY_APPROVAL_REQUIRED,
    HU_ERR_SECURITY_RATE_LIMITED,
    HU_ERR_SECURITY_LOCKOUT,

    HU_ERR_PERIPHERAL_NOT_CONNECTED,
    HU_ERR_PERIPHERAL_IO,
    HU_ERR_PERIPHERAL_FLASH_FAILED,
    HU_ERR_PERIPHERAL_DEVICE_NOT_FOUND,

    HU_ERR_TUNNEL_START_FAILED,
    HU_ERR_TUNNEL_URL_NOT_FOUND,

    HU_ERR_GATEWAY_RATE_LIMITED,
    HU_ERR_GATEWAY_BODY_TOO_LARGE,
    HU_ERR_GATEWAY_AUTH,

    HU_ERR_CRYPTO_ENCRYPT,
    HU_ERR_CRYPTO_DECRYPT,
    HU_ERR_CRYPTO_HMAC,

    HU_ERR_JSON_PARSE,
    HU_ERR_JSON_TYPE,
    HU_ERR_JSON_DEPTH,

    HU_ERR_INTERNAL,
    HU_ERR_SUBAGENT_TOO_MANY,
    HU_ERR_CANCELLED,

    HU_ERR_LIMIT_REACHED,

    HU_ERR_FLEET_DEPTH_EXCEEDED,
    HU_ERR_FLEET_SPAWN_CAP,
    HU_ERR_FLEET_BUDGET_EXCEEDED,

    HU_ERR_COUNT
} hu_error_t;

const char *hu_error_string(hu_error_t err);

#endif
